name: Compile React app

# Controls when the action will run. 
on: [push]

jobs:
  build:
    env: 
      CI: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Download required modules
      run: |
        cd reactjs
        npm install
    - name: Build web app
      run: |
        cd reactjs
        npm run build